### ISSUE TITLE
Add person: After"you mean XXX", answer"yes", reply"undefine"

### ISSUE THREAD

**Issue by changchauncey** [senseplus/sense-plus-webapp#6]

**Comment by derekmma** [comment]
![screen shot 2017-07-11 at 21 38 40](https://user-images.githubusercontent.com/25177003/28097943-5855ed34-6681-11e7-910e-f7b98b771f28.png)

**Comment by derekmma** [comment]
server problem. forget to parse return result. Resolved now.
